<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-05-16 16:16
=======
# Generated by Django 2.2.1 on 2019-05-16 16:24
>>>>>>> Adicionar Servicos e Publicacoes (incompleto)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('missao', models.TextField()),
                ('visao', models.TextField()),
                ('valores', models.TextField()),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quem somos',
            },
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=100)),
                ('descrição', models.TextField()),
            ],
        ),
    ]
