# Generated by Django 2.2.1 on 2019-05-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=300, null=True, verbose_name='Link')),
                ('image', models.ImageField(null=True, upload_to='media/publicacoes', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('missao', models.TextField()),
                ('visao', models.TextField()),
                ('valores', models.TextField()),
            ],
            options={
                'verbose_name': 'Quem somos',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('text', models.TextField(null=True, verbose_name='Descrição')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='media/servicos', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created_date'],
            },
        ),
    ]
