# Generated by Django 2.2.1 on 2019-05-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='descrição',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='servicos',
            old_name='título',
            new_name='title',
        ),
    ]
