# Generated by Django 2.2.1 on 2019-05-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConfiguration',
            new_name='QuemSomos',
        ),
    ]
