# Generated by Django 2.2.1 on 2019-05-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parceiros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceiros',
            options={'ordering': ['title'], 'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
    ]
