# Generated by Django 2.2.1 on 2019-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190518_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
