# Generated by Django 2.2.1 on 2019-05-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190516_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['-created_date']},
        ),
    ]
