# Generated by Django 2.2.1 on 2019-05-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190516_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='updated_date',
        ),
    ]
