# Generated by Django 2.2.1 on 2019-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190518_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['title'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='image',
            field=models.ImageField(null=True, upload_to='media/parceiros', verbose_name='Imagem'),
        ),
    ]
