# Generated by Django 2.2.1 on 2019-05-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190516_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemsomos',
            name='maintenance_mode',
        ),
    ]
