# Generated by Django 2.2.1 on 2019-05-16 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190516_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['-created_date'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='servicos',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicos',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
