# Generated by Django 2.2.1 on 2019-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190518_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem', models.ImageField(upload_to='media/depoimentos', verbose_name='Imagem')),
                ('vinculo', models.CharField(max_length=100, verbose_name='Vínculo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'ordering': ['created_date'],
            },
        ),
    ]
