# Generated by Django 2.2.1 on 2019-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_depoimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentos',
            name='imagem',
            field=models.ImageField(upload_to='media/depoimentos', verbose_name='Foto'),
        ),
    ]
