# Generated by Django 2.2.1 on 2019-05-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190516_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacoes',
            new_name='Publi',
        ),
    ]
