# Generated by Django 2.2.1 on 2019-05-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190516_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publi',
            new_name='Publicacoes',
        ),
    ]
