# Generated by Django 2.2.1 on 2019-05-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190523_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimentos',
            name='imagem',
            field=models.ImageField(upload_to='depoimentos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='image',
            field=models.ImageField(null=True, upload_to='parceiros/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='image',
            field=models.ImageField(null=True, upload_to='publicacoes/', verbose_name='Imagem'),
        ),
    ]
