# Generated by Django 2.2.1 on 2019-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190523_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='text',
            field=models.TextField(max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
