# Generated by Django 2.2.1 on 2019-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190516_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacoes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicacoes/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
