# Generated by Django 2.2.1 on 2019-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190517_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicacoes/images', verbose_name='Imagem'),
        ),
    ]
