# Generated by Django 2.2.1 on 2019-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servicos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='image',
            field=models.ImageField(null=True, upload_to='publicacoes/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='image',
            field=models.ImageField(null=True, upload_to='publicacoes/images', verbose_name='Imagem'),
        ),
    ]
