# Generated by Django 2.2.1 on 2019-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190517_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacoes',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
