# Generated by Django 2.2.1 on 2019-05-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publicacoes_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
