# Generated by Django 2.2.1 on 2019-05-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190517_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='image',
            field=models.ImageField(null=True, upload_to='media/publicacoes/images', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='image',
            field=models.ImageField(null=True, upload_to='media/servicos/images', verbose_name='Imagem'),
        ),
    ]
