# Generated by Django 2.2.1 on 2019-05-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190517_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publicacoes',
            name='url',
            field=models.URLField(max_length=300, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='text',
            field=models.TextField(null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
